import { Router } from 'express';
import { z } from 'zod';
import { objectId } from '@kmart/shared';
import { authenticate } from '../../middleware/auth.js';
import { rateLimit } from '../../middleware/rate-limit.js';
import { Review,DeviceToken,Notification,SearchEvent,AnalyticsEvent,ProductView,Banner } from './models.js';
import { Product,Category } from '../catalog/models.js';
import { createReview,recordEvent,recommendations } from './service.js';
export const engagementRouter=Router();
engagementRouter.get('/home',async(_req,res)=>{const [banners,categories,featured,trending,newArrivals]=await Promise.all([Banner.find({active:true,$and:[{$or:[{startsAt:null},{startsAt:{$lte:new Date()}}]},{$or:[{expiresAt:null},{expiresAt:{$gt:new Date()}}]}]}).limit(6).lean(),Category.find({active:true}).limit(12).lean(),Product.find({active:true,featured:true}).limit(8).lean(),Product.find({active:true}).sort({soldCount:-1}).limit(8).lean(),Product.find({active:true,newArrival:true}).sort({_id:-1}).limit(8).lean()]);res.json({success:true,data:{banners,categories,featured,trending,newArrivals}});});
engagementRouter.get('/products/:id/reviews',async(req,res)=>res.json({success:true,data:await Review.find({productId:objectId.parse(req.params.id),status:'published'}).select('-reportedBy -helpfulUserIds -userId').sort({_id:-1}).limit(30).lean()}));
engagementRouter.use(authenticate);
engagementRouter.post('/products/:id/reviews',rateLimit('review',5,3600000),async(req,res)=>res.status(201).json({success:true,data:await createReview(req.auth!.userId,objectId.parse(req.params.id),z.object({rating:z.number().int().min(1).max(5),text:z.string().trim().min(5).max(3000),images:z.array(z.url().refine(s=>s.startsWith('https://'))).max(5).default([])}).strict().parse(req.body))}));
engagementRouter.post('/reviews/:id/:action',async(req,res)=>{const field=z.enum(['helpful','report']).parse(req.params.action)==='helpful'?'helpfulUserIds':'reportedBy';await Review.updateOne({_id:objectId.parse(req.params.id),status:'published'},{$addToSet:{[field]:req.auth!.userId}});res.json({success:true,data:{}});});
engagementRouter.get('/recommendations',async(req,res)=>res.json({success:true,data:await recommendations(req.auth!.userId,z.enum(['for-you','recent','similar','bought-together']).default('for-you').parse(req.query.kind),objectId.optional().parse(req.query.productId))}));
engagementRouter.post('/events',rateLimit('events',120),async(req,res)=>{const input=z.object({name:z.enum(['product_view','search','search_result_click','add_to_cart','remove_from_cart','wishlist_add','checkout_started','payment_started','ai_message','ai_product_click','ai_add_to_cart']),productId:objectId.optional(),query:z.string().max(200).optional(),source:z.enum(['catalog','ai','search']).optional()}).strict().parse(req.body);await recordEvent(req.auth!.userId,input);res.status(202).json({success:true,data:{}});});
engagementRouter.get('/search-history',async(req,res)=>res.json({success:true,data:await SearchEvent.find({userId:req.auth!.userId}).sort({_id:-1}).limit(20).lean()}));
engagementRouter.delete('/search-history',async(req,res)=>{await Promise.all([SearchEvent.deleteMany({userId:req.auth!.userId}),ProductView.deleteMany({userId:req.auth!.userId}),AnalyticsEvent.deleteMany({userId:req.auth!.userId})]);res.json({success:true,data:{}});});
engagementRouter.put('/devices',async(req,res)=>{const input=z.object({token:z.string().regex(/^(ExponentPushToken|ExpoPushToken)\[[\w-]+\]$/),platform:z.enum(['ios','android'])}).strict().parse(req.body);await DeviceToken.updateOne({token:input.token},{$set:{...input,userId:req.auth!.userId,disabledAt:null}},{upsert:true});res.json({success:true,data:{}});});
engagementRouter.delete('/devices',async(req,res)=>{await DeviceToken.deleteMany({userId:req.auth!.userId,token:z.string().max(200).parse(req.body.token)});res.json({success:true,data:{}});});
engagementRouter.get('/notifications',async(req,res)=>res.json({success:true,data:await Notification.find({userId:req.auth!.userId}).sort({_id:-1}).limit(50).lean()}));
engagementRouter.patch('/notifications/:id',async(req,res)=>{await Notification.updateOne({_id:objectId.parse(req.params.id),userId:req.auth!.userId},{$set:{readAt:new Date()}});res.json({success:true,data:{}});});
