import { Router } from 'express';
import { z } from 'zod';
import { objectId,cartItemSchema,addressSchema,checkoutSchema } from '@kmart/shared';
import { authenticate } from '../../middleware/auth.js';
import { rateLimit } from '../../middleware/rate-limit.js';
import { getCart,setCart } from './cart-service.js';
import { checkout,transitionOrder,requestReturn } from './order-service.js';
import { Address,Wishlist,Order } from './models.js';
import { Product } from '../catalog/models.js';
import { requireValue } from '../../lib/errors.js';
import { enabledProviders,initiatePayment } from './payment-service.js';
export const commerceRouter=Router();
commerceRouter.use(authenticate);
commerceRouter.get('/cart',async(req,res)=>res.json({success:true,data:await getCart(req.auth!.userId)}));
commerceRouter.put('/cart',async(req,res)=>res.json({success:true,data:await setCart(req.auth!.userId,z.array(cartItemSchema).max(50).parse(req.body.items))}));
commerceRouter.post('/cart/merge',async(req,res)=>res.json({success:true,data:await setCart(req.auth!.userId,z.array(cartItemSchema).max(50).parse(req.body.items),true)}));
commerceRouter.get('/wishlist',async(req,res)=>{const w=await Wishlist.findOne({userId:req.auth!.userId});res.json({success:true,data:await Product.find({_id:{$in:w?.productIds??[]},active:true}).limit(100).lean()});});
commerceRouter.put('/wishlist/:id',async(req,res)=>{const id=objectId.parse(req.params.id);requireValue(await Product.exists({_id:id,active:true}));await Wishlist.updateOne({userId:req.auth!.userId},{$addToSet:{productIds:id}},{upsert:true});res.json({success:true,data:{}});});
commerceRouter.delete('/wishlist/:id',async(req,res)=>{await Wishlist.updateOne({userId:req.auth!.userId},{$pull:{productIds:objectId.parse(req.params.id)}});res.json({success:true,data:{}});});
commerceRouter.get('/addresses',async(req,res)=>res.json({success:true,data:await Address.find({userId:req.auth!.userId}).limit(50).lean()}));
commerceRouter.post('/addresses',async(req,res)=>res.status(201).json({success:true,data:await Address.create({...addressSchema.parse(req.body),userId:req.auth!.userId})}));
commerceRouter.put('/addresses/:id',async(req,res)=>res.json({success:true,data:requireValue(await Address.findOneAndUpdate({_id:objectId.parse(req.params.id),userId:req.auth!.userId},{$set:addressSchema.parse(req.body)},{new:true,runValidators:true}))}));
commerceRouter.delete('/addresses/:id',async(req,res)=>{requireValue(await Address.findOneAndDelete({_id:objectId.parse(req.params.id),userId:req.auth!.userId}));res.json({success:true,data:{}});});
commerceRouter.get('/payments/providers',(_req,res)=>res.json({success:true,data:enabledProviders()}));
commerceRouter.post('/checkout',rateLimit('checkout',10),async(req,res)=>res.status(201).json({success:true,data:await checkout(req.auth!.userId,z.string().min(16).max(100).parse(req.headers['idempotency-key']),checkoutSchema.parse(req.body))}));
commerceRouter.get('/orders',async(req,res)=>res.json({success:true,data:await Order.find({userId:req.auth!.userId}).sort({_id:-1}).limit(50).lean()}));
commerceRouter.get('/orders/:id',async(req,res)=>res.json({success:true,data:requireValue(await Order.findOne({_id:objectId.parse(req.params.id),userId:req.auth!.userId}).lean())}));
commerceRouter.post('/orders/:id/cancel',async(req,res)=>{z.object({confirmed:z.literal(true)}).strict().parse(req.body);res.json({success:true,data:await transitionOrder(objectId.parse(req.params.id),'cancelled',{userId:req.auth!.userId,admin:false})});});
commerceRouter.post('/orders/:id/return',async(req,res)=>{const {reason,confirmed:_confirmed}=z.object({reason:z.string().min(10).max(1000),confirmed:z.literal(true)}).strict().parse(req.body);res.status(201).json({success:true,data:await requestReturn(req.auth!.userId,objectId.parse(req.params.id),reason)});});
commerceRouter.post('/orders/:id/pay',rateLimit('payment',10),async(req,res)=>res.json({success:true,data:await initiatePayment(req.auth!.userId,objectId.parse(req.params.id))}));
